name: Housekeeping

on:
    workflow_dispatch:
    push:

jobs:
    housekeeping:
        runs-on: ubuntu-latest
        steps:
          -   uses: "actions/checkout@v2"
          -   uses: "shivammathur/setup-php@v2"
              with:
                php-version: "8.0"
          -   uses: "ramsey/composer-install@v1"
          -   name: "Sync embedded code blocks"
              run: "composer embed-files"
          -   name: "Run PHPCBF"
              run: "./vendor/bin/phpcbf; if [ $? -eq 1 ]; then exit 0; fi"
          -   uses: "stefanzweifel/git-auto-commit-action@v4"

