name: Embed code in README

on:
    workflow_dispatch:
    push:

jobs:
    embed-code:
        runs-on: ubuntu-latest
        steps:
          -   uses: "actions/checkout@v2"
          -   uses: "shivammathur/setup-php@v2"
              with:
                php-version: "8.0"
          -   uses: "ramsey/composer-install@v1"
          -   name: "Run PHPUnit"
              run: "composer embed-files"
          -   uses: "stefanzweifel/git-auto-commit-action@v4"

